// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpqtOPB3WcC_zERV4G4iaE0XfuINGRWAo',
    appId: '1:407701761523:web:7ddf53ea3459c3513eb686',
    messagingSenderId: '407701761523',
    projectId: 'policylens-9a800',
    authDomain: 'policylens-9a800.firebaseapp.com',
    storageBucket: 'policylens-9a800.firebasestorage.app',
    measurementId: 'G-NNDVF0VHD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD825uuPdiBm7oJeMgp01tOYxmNeTVjNhY',
    appId: '1:407701761523:android:f1873d83f62c1f313eb686',
    messagingSenderId: '407701761523',
    projectId: 'policylens-9a800',
    storageBucket: 'policylens-9a800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFFZ6LdSOECiKfBvQg5FoqkFkfOLGhUUA',
    appId: '1:407701761523:ios:4083bda993a808813eb686',
    messagingSenderId: '407701761523',
    projectId: 'policylens-9a800',
    storageBucket: 'policylens-9a800.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFFZ6LdSOECiKfBvQg5FoqkFkfOLGhUUA',
    appId: '1:407701761523:ios:342dadeda7449a173eb686',
    messagingSenderId: '407701761523',
    projectId: 'policylens-9a800',
    storageBucket: 'policylens-9a800.firebasestorage.app',
    iosBundleId: 'com.example.policylens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpqtOPB3WcC_zERV4G4iaE0XfuINGRWAo',
    appId: '1:407701761523:web:298a18a913f1c2303eb686',
    messagingSenderId: '407701761523',
    projectId: 'policylens-9a800',
    authDomain: 'policylens-9a800.firebaseapp.com',
    storageBucket: 'policylens-9a800.firebasestorage.app',
    measurementId: 'G-2R7V93HNY2',
  );
}
